/*CREATE TABLE ESTADO (
   ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
	UF VARCHAR(255),
	NOME VARCHAR(255),
	PRIMARY KEY (ID)
);*/

Insert into ESTADO
   (ID, UF, NOME)
 Values
   (12, 'AC', 'Acre');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (27, 'AL', 'Alagoas');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (16, 'AP', 'Amapá');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (13, 'AM', 'Amazonas');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (29, 'BA', 'Bahia');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (23, 'CE', 'Ceará');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (53, 'DF', 'Distrito Federal');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (32, 'ES', 'Espírito Santo');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (52, 'GO', 'Goiás');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (21, 'MA', 'Maranhão');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (51, 'MT', 'Mato Grosso');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (50, 'MS', 'Mato Grosso do Sul');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (31, 'MG', 'Minas Gerais');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (15, 'PA', 'Pará');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (25, 'PB', 'Paraíba');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (41, 'PR', 'Paraná');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (26, 'PE', 'Pernambuco');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (22, 'PI', 'Piauí');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (33, 'RJ', 'Rio de Janeiro');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (24, 'RN', 'Rio Grande do Norte');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (43, 'RS', 'Rio Grande do Sul');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (11, 'RO', 'Rondônia');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (14, 'RR', 'Roraima');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (42, 'SC', 'Santa Catarina');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (35, 'SP', 'São Paulo');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (28, 'SE', 'Sergipe');
Insert into ESTADO
   (ID, UF, NOME)
 Values
   (17, 'TO', 'Tocantins');
COMMIT;
